//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Warsztat.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Addresses
    {
        public long ID_address { get; set; }
        public long ID_user { get; set; }
        public string Street { get; set; }
        public Nullable<int> Number { get; set; }
        public string City { get; set; }
        public string PostCode { get; set; }
    
        public virtual Users Users { get; set; }
    }
}
