//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Warsztat.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderDetails
    {
        public long ID_orderDetail { get; set; }
        public Nullable<long> ID_order { get; set; }
        public Nullable<long> ID_part { get; set; }
        public Nullable<int> quantity { get; set; }
        public Nullable<decimal> Brutto { get; set; }
        public Nullable<decimal> Netto { get; set; }
    
        public virtual Orders Orders { get; set; }
        public virtual Parts Parts { get; set; }
    }
}
